server:
  port: 8270
spring:
 
  datasource:
    url: jdbc:sqlserver://;serverName=DESKTOP-R1S09TJ;instanceName=MSSQL2019;port=1433;encrypt=true;trustServerCertificate=true;databaseName=minsadb
       
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    #database: postgresql
    database-platform: org.hibernate.dialect.SQLserverDialect
